# Generated by Django 3.2 on 2021-05-12 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('old_town_road', '0002_auto_20210512_2028'),
    ]

    operations = [
        migrations.AddField(
            model_name='gasstation',
            name='location',
            field=models.IntegerField(default=-1),
        ),
    ]
